config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  resources :toilets do
    resources :bookings, only: [ :new, :create, :destroy ]
    resources :reviews, only: [ :new, :create, :destroy ]
  end

  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :renter, class_name: 'User'
  belongs_to :toilet

  def owner
    @toilet = self.toilet
    return @toilet.owner
  end
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :toilet
  validates :url, presence: true
  mount_uploader :url, PhotoUploader
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :toilet
  belongs_to :user
  validates :content, presence: true
end

app/models/toilet.rb
class Toilet < ApplicationRecord
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  belongs_to :owner, class_name: 'User'
  has_many :bookings, dependent: :destroy
  has_many :renters, through: :bookings, class_name: 'User'
  has_many :images, dependent: :destroy
  has_many :reviews, dependent: :destroy
  validates :title, presence: true
  validates :description, presence: true
  validates :location, presence: true
  validates :address, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :toilets, through: :bookings
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :toilets, foreign_key: 'owner_id'
  has_many :bookings, foreign_key: 'renter_id'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  # before_action :configure_permitted_parameters, if: :devise_controller?

  # def configure_permitted_parameters
  #   # For additional fields in app/views/devise/registrations/new.html.erb
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

  #   # For additional in app/views/devise/registrations/edit.html.erb
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
  end

  def create
    @booking = Booking.new(booking_params)
    @toilet = Toilet.find(params[:toilet_id])
    @booking.renter = current_user
    @booking.toilet = @toilet
    if @booking.save
      redirect_to dashboard_path(@booking)
    else
      render :new
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy
    # redirect_to dashboard_path
  end

  private

  def booking_params
    params.require(:booking).permit(:date, :time)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end

  def dashboard
    @toilets = Toilet.all
    @bookings = Booking.all
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  # def new
  #   @review = Review.new
  # end

  def create
    @review = Review.new(review_params)
    @toilet = Toilet.find(params[:toilet_id])
    @review.user = current_user
    @review.toilet = @toilet
    if @review.save
      respond_to do |format|
        format.html { redirect_to toilet_path(@toilet) }
        format.js  # <-- will render `app/views/reviews/create.js.erb`
      end
    else
      respond_to do |format|
        format.html { render 'toilets/show' }
        format.js  # <-- idem
      end
    end
  end

  def destroy

    @review = Review.find(params[:id])
    @toilet = @review.toilet
    @review.destroy
    # redirect_to toilet_path(@toilet)
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/controllers/toilets_controller.rb
class ToiletsController < ApplicationController
  before_action :set_toilet, only: [:show, :edit, :update, :destroy]
  skip_before_action :authenticate_user!, only: [:index]

  def index
    @toilets = Toilet.all
    @toilets = Toilet.geocoded
    @markers = @toilets.map do |toilet|
      {
        lat: toilet.latitude,
        lng: toilet.longitude,
        infoWindow: render_to_string(partial: "info_window", locals: { toilet: toilet })
      }
    end
  end

  def show
    @booking = Booking.new
    @review = Review.new
    # @toilet = Toilet.geocoded
    @marker =
      [{
        lat: @toilet.latitude,
        lng: @toilet.longitude
        # infoWindow: render_to_string(partial: "info_window", locals: { toilet: @toilet })
      }]
  end

  def new
    @toilet = Toilet.new
  end

  def create
    @toilet = Toilet.new(toilet_params)
    @toilet.owner = current_user
    params[:toilet][:images].each do |image_attributes|
      Image.create(url: image_attributes, toilet: @toilet)
    end
    if @toilet.save
      redirect_to toilet_path(@toilet)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @toilet.update(toilet_params)
    redirect_to toilet_path(@toilet)
  end

  def destroy
    @toilet.destroy
    # redirect_to dashboard_path
  end

  private

  def set_toilet
    @toilet = Toilet.find(params[:id])
  end

  def toilet_params
    params.require(:toilet).permit(:title, :description, :location, :address, :price, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/destroy.js.erb
document.getElementById("booking-<%= @booking.id %>").remove();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Air 💩 PNP</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= favicon_link_tag asset_path('favicon.jpg') %>
    <%= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/dashboard.html.erb
<div class="container">

  <div class="row d-flex justify-content-center">
      <div class="page-title welcome">
        <h1>Welcome <%= current_user.first_name %> <br> </h1>
      </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-6">
      <div class="page-title">
        <h1>Booked Toilets</h1>
      </div>
    </div>
    <div class="col-6">
      <div class="page-title">
        <h1>My Toilets</h1>
      </div>
    </div>
  </div>

  <div class="row d-flex justify-content-center">
    <div class="col-6">
      <% @bookings.each do |booking| %>

        <% if booking.renter == current_user %>
          <div id="booking-<%= booking.id %>">
            <%= link_to toilet_path(booking.toilet), class: "card-link" do  %>
              <div class="card-dashboard">
                <div class="card-toilet">
                  <div class="card-info">
                    <div class="card-title"><%= booking.toilet.title %></div>
                    <div class="card-location"><%= booking.toilet.location %></div>
                  </div>
                  <% if booking.toilet.images.empty? %>
                      <div  class= "card-image" style=" background-image: url('https://i.pinimg.com/originals/72/a9/3f/72a93f8f5eb98d80df21d63924771142.jpg');"></div>
                    <% else %>
                      <div  class= "card-image" style=" background-image: url('<%= cl_image_path booking.toilet.images.first.url %>');"></div>
                    <% end %>
                  <div class="card-price"><%= booking.toilet.price %> DKK.-</div>
                </div>

                <div class="card-cta">
                  <%= link_to toilet_booking_path(booking.toilet, booking),
                     method: :delete,
                     remote: true,
                     class: "flush",
                     data: { sound_url: asset_path("flush.mp3") } do %>
                    <div class="button-fill card-button">Cancel Booking</div>
                  <% end %>
                    <div class="booking-details">Your booking is on <%= booking.date.strftime("%b %d %Y") %> at <%= booking.time.strftime("%H:%M") %> </div>
                </div>
              </div>
            <% end %>
          </div>
        <% end %>

      <% end %>
    </div>

    <div class="col-6">
      <% @toilets.each do |toilet| %>
        <% if toilet.owner == current_user %>

          <div id="toilet-<%= toilet.id %>">
            <%= link_to toilet_path(toilet), class: "card-link" do  %>
              <div class="card-dashboard">

                <div class="card-toilet">
                  <div class="card-info">
                    <div class="card-title"><%= toilet.title %></div>
                    <div class="card-location"><%= toilet.location %></div>
                  </div>
                  <% if toilet.images.empty? %>
                      <div  class= "card-image" style=" background-image: url('https://i.pinimg.com/originals/72/a9/3f/72a93f8f5eb98d80df21d63924771142.jpg');"></div>
                    <% else %>
                      <div  class= "card-image" style=" background-image: url('<%= cl_image_path toilet.images.first.url %>');"></div>
                    <% end %>
                  <div class="card-price"><%= toilet.price %> DKK.-</div>
                </div>
                <div class="card-cta">

                  <%= link_to edit_toilet_path(toilet) do %>
                    <div class="button-fill card-button">Edit Toilet</div>
                  <% end %>
                  <%= link_to toilet_path(toilet),
                     method: :delete,
                     remote: true,
                     class: "flush",
                     data: { sound_url: asset_path("flush.mp3") } do %>
                    <div class="button-fill card-button">Flush Toilet</div>
                  <% end %>
              </div>
                </div>

              </div>
            <% end %>

        <% end %>
      <% end %>
    </div>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'flush-sound' %>

app/views/pages/home.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 d-flex align-items-baseline">
      <span class="landing-text" id="banner-typed-text">
      </span>
    </div>
  </div>
  <div class="row d-flex justify-content-center">
    <%= link_to toilets_path, class: "button-link" do%>
      <div class="button-container">
        <div class="button-inactive-large">
          See all toilets
        </div>
        <%end%>
      </div>
  </div>
</div>

app/views/reviews/_form.html.erb
<%= simple_form_for([toilet, review], remote: true) do |f| %>
  <%= f.input :content, label: "Please leave a review" %>
  <%= f.submit "Submit" %>
<% end %>

app/views/reviews/_show.html.erb
<div class="speech-wrapper d-flex" id="review-<%=review.id %>">
  <div class="bubble">
    <div class="txt">
      <p class="name"> <%= review.user.first_name %> <%= review.user.last_name %></p>
      <p class="message"> <%= review.content %></p>
      <span class="timestamp"> <%= review.created_at.strftime("%m-%e-%y %H:%M") %> </span>
    </div>
  <div class="bubble-arrow"></div>
   <% if review.user == current_user %>
    <%= link_to toilet_review_path(review.toilet, review),
        method: :delete,
        remote: true,
        data: { confirm: "Are you sure?" } do %>
      <div class="small-delete-button-fill card-button">Delete</div>
    <% end %>
  <% end %>
  </div>
</div>

app/views/reviews/create.js.erb
function refreshForm(innerHTML) {
  const newReviewForm = document.getElementById('new_review');
  newReviewForm.innerHTML = innerHTML;
}

function addReview(reviewHTML) {
  const reviews = document.getElementById('reviews');
  reviews.insertAdjacentHTML('beforeend', reviewHTML);
}

function removeMessage() {
  const message = document.getElementById("message").remove();
}

<% if @review.errors.any? %>
  refreshForm('<%= j render "reviews/form", toilet: @toilet, review: @review %>');
<% else %>
  <% if @toilet.reviews.length == 1 %>
    removeMessage();
  <% end %>
    addReview('<%= j render "reviews/show", review: @review %>');
    refreshForm('<%= j render "reviews/form", toilet: @toilet, review: Review.new %>');

<% end %>

app/views/reviews/destroy.js.erb
const reviewBox = document.getElementById("reviews");
document.getElementById("review-<%=@review.id %>").remove();
<% if @toilet.reviews.empty? %>
  reviewBox.insertAdjacentHTML('beforeend', '<span>There are no reviews for this toilet!</span>');
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar fixed-top navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to toilets_path, class: "navbar-brand" do %>
    <div class="nav-logo">AIR 💩 PNP</div>
    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
          <%= link_to new_toilet_path, class: "nav-link" do %>
            <div class="button-nofill">Add Toilet</div>
          <% end %>

          <%= link_to dashboard_path, class: "nav-link" do %>
            <div class="button-nofill">Dashboard</div>
          <% end %>
        <li class="nav-item dropdown">
          <%= image_tag "https://blog.fromjapan.co.jp/en/wp-content/uploads/2015/08/Poop_2.jpg", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Edit profile", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <div class="row">
          <%= link_to new_user_registration_path, class: "nav-link" do %>
              <div class="button-fill">Sign Up</div>
            <% end %>
            <%= link_to new_user_session_path, class: "nav-link" do %>
              <div class="button-nofill">Log In</div>
            <% end %>
          <% end %>
          </div>
        </li>
    </ul>
  </div>
</div>

app/views/toilets/_carousel.html.erb
<div class="carousel-inner">
  <% toilet.images.each_with_index do |image, index| %>
    <% if index == 0 %>
      <div class="carousel-item active">
        <img class="d-block" src="<%= cl_image_path image.url %>" alt="First slide">
      </div>
    <% else %>
      <div class="carousel-item">
        <img class="d-block" src="<%= cl_image_path image.url %>" alt="First slide">
      </div>
    <% end %>
  <% end %>
</div>
<a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
  <span class="carousel-control-prev-icon" aria-hidden="true"></span>
  <span class="sr-only">Previous</span>
</a>
<a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
  <span class="carousel-control-next-icon" aria-hidden="true"></span>
  <span class="sr-only">Next</span>
</a>

app/views/toilets/_form.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 offset-sm-4">
      <%= simple_form_for(@toilet) do |f| %>
        <% if @toilet.errors.any? %>
          <div class="errors-container">
            <ul>
              <% @toilet.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>
        <%= f.input :title %>
        <%= f.input :description %>
        <%= f.input :location %>
        <%= f.input :address %>
        <%= f.input :price  %>
        <%= f.file_field :images, multiple: true%>
        <%= f.submit "Add!" %>
      <% end %>
    </div>
  </div>
</div>

app/views/toilets/_info_window.html.erb
<%= link_to toilet_path(toilet), class: "card-link" do  %>
  <div class="card-map">
    <div class="card-map-info">
      <div class="card-map-title"><%= toilet.title %></div>
      <div class="card-map-location"><%= toilet.location %></div>
    </div>
    <% if toilet.images.empty? %>
        <div  class= "card-map-image" style=" background-image: url('https://i.pinimg.com/originals/72/a9/3f/72a93f8f5eb98d80df21d63924771142.jpg');"></div>
      <% else %>
        <div  class= "card-map-image" style=" background-image: url('<%= cl_image_path toilet.images.first.url %>');"></div>
      <% end %>
    <div class="card-map-price"><%= toilet.price %> DKK.-</div>
  </div>
<% end %>

app/views/toilets/destroy.js.erb
document.getElementById("toilet-<%=@toilet.id %>").remove();

app/views/toilets/edit.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="show-title">
      <h1> Edit your toilet </h1>
    </div>
  </div>
</div>


<%= render 'form', toilet: @toilet %>

app/views/toilets/index.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="page-title">
      <h1>Browse the seats that'll suit your butt</h1>
    </div>
  </div>
  <div
    id="map"
    style="width: 100%;
    height: 300px;"
    data-markers="<%= @markers.to_json %>"
    data-mapbox-api-key= "<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <br>
  <div class="row d-flex">
    <% @toilets.each do |toilet| %>
      <div class="col-md-6">
        <%= link_to toilet_path(toilet), class: "card-link" do  %>
        <div class="card-index">

          <div class="card-toilet radius-all">
            <div class="card-info">
              <div class="card-title"><%= toilet.title %></div>
              <div class="card-location"><%= toilet.location %></div>
            </div>
            <% if toilet.images.empty? %>
                <div  class= "card-image radius-right" style=" background-image: url('https://i.pinimg.com/originals/72/a9/3f/72a93f8f5eb98d80df21d63924771142.jpg');"></div>
              <% else %>
                <div  class= "card-image radius-right" style=" background-image: url('<%= cl_image_path toilet.images.first.url %>');"></div>
              <% end %>
            <div class="card-price"><%= toilet.price %> DKK.-</div>
          </div>
        <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/toilets/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="show-title">
      <h1> Add a new toilet </h1>
    </div>
  </div>
</div>

<%= render 'form', toilet: @toilet %>

app/views/toilets/show.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="show-title">
      <h1> <%= @toilet.title %> </h1>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-8 mb-4">
      <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <%= render 'carousel', toilet: @toilet %>
      </div>

      <div class="show-card d-flex align-items-center justify-content-between">
        <div class="sub-title">
          <h3>This toilet in <strong> <%= @toilet.location %> </strong> is hosted by <strong> <%= @toilet.owner.first_name%> <%= @toilet.owner.last_name %> </strong> </h3>
        </div>
        <div>
          <img src="https://blog.fromjapan.co.jp/en/wp-content/uploads/2015/08/Poop_2.jpg" alt="" class="avatar-large">
        </div>
      </div>

      <div class="show-card">
        <h3>Details</h3>
        <ul>
          <strong>DKK</strong> <%= @toilet.price %> per use
          <% @toilet.description.split(',').each do |description| %>
            <li class="d-flex">
              <div>
                <i class="fas fa-toilet mr-2"></i>
              </div>
              <%= description %>
            </li>
          <% end %>
        </ul>
      </div>

      <div class="show-card" id="reviews">
        <h3>Reviews</h3>
        <% if @toilet.reviews.empty? %>
          <p id="message">There are no reviews for this toilet!</p>
        <% else %>
            <% @toilet.reviews.each do |review| %>
               <%= render 'reviews/show', review: review %>
            <% end %>
        <% end %>
      </div>

      <div class="show-card">
        <%= render 'reviews/form', toilet: @toilet, review: @review %>
      </div>

    </div>
    <div class="side-wrap col-sm-4">
      <div class="sidebar">
        <div class="booking-card">
            <%= simple_form_for [@toilet, @booking] do |f| %>
              <%= f.input :date, as: :date_time_picker, input_html:
                { data:
                  {
                    date_format: "YYYY-MM-DD",
                  }
                }  %>
              <%= f.input :time, as: :date_time_picker, input_html:
              { data:
                  {

                    date_format: 'HH:mm:ss',
                    pickDate:false,
                    date_side_by_side: true,
                    date_min_date: Time.current.strftime('%Y-%m-%d')
                  }
                } %>
              <%= f.submit "Book!" %>
            <% end %>
        </div>
        <div
          id="showmapbox"
          style="width: 100%;
          height: 300px;"
          data-markers="<%= @marker.to_json %>"
          data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"
        ></div>
      </div>
    </div>
<!--     <br>
    <div class="col-sm-8 mb-4">

    </div> -->
  </div>
</div>